[package]
name = "frac"
edition = "2018"
version = "1.0.2"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.xyz>"]
homepage = "https://github.com/nekodjin/frac"
repository = "https://github.com/nekodjin/frac"
description = "Rational Number Data Type"
